groups:
  flat:
    prefix: flat
    metrics:
      silknetData:
        target:
          type: request
          headers: {'Accept': 'application/json', 'authority': 'silknet.com'}
          url: 'https://silknet.com/api/view/services/fixes-balance?phoneNumber=91151413&numberType=ACCOUNT'
        sending:
          target: post
          url: 'http://masto:gj448p1QLpcaVW90RI5dc10m3NHp0e4k68DtMsV4896m14zx3UoSc2ldhLoBQ0u7@45.140.179.208:9091/metrics/job/pushgateway/instance/flat'
          keys_json:
            debt:
              calc: '%v/100'
            advance:
              calc: '%v/100'
          format: '%p_%k_%n %v'
        time: 60
  test: # random key
    prefix: mytest20
    metrics:
      sum: # random key
        target:
          type: math
          expression: 2 + 3
        sending:
          target: stdout
          format: '%p.%k: %v'
        time: 20
  ara: # random key
    prefix: mytest30
    metrics:
      ddd: # random key
        target:
          type: math
          expression: 2 + 2
        sending:
          target: stdout
          format: '%p.%k: %v'
        time: 30
  diah: # random key
    prefix: mytest40
    metrics:
      ppr: # random key
        target:
          type: math
          expression: 2 + 1
        sending:
          target: stdout
          format: '%p.%k: %v'
        time: 40
  ki: # random key
    prefix: mytest50
    metrics:
      ppr: # random key
        target:
          type: math
          expression: 2 + 4
        sending:
          target: stdout
          format: '%p.%k: %v'
          calc: '%v/100'
        time: 1
      pi: # random key
        target:
          type: math
          expression: 10+10
        sending:
          target: stdout
          format: '%p.%k: %v'
        time: 5